version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:88255632@db:5432/shopperdb"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:14
    container_name: db-shopperdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 88255632
      POSTGRES_DB: shopperdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
